/**
 * Runtime texture atlas for the flat pixel-art character sprites (generated by
 * tools/gen_atlas.py -> assets/atlas.png). Loaded async at startup; until it's
 * ready, callers fall back to the procedural drawing in sprites.ts.
 *
 * The atlas is laid out one entity per ROW, with animation frames packed
 * left-to-right per state (idle / walk / attack). The SPRITES index below is
 * emitted verbatim by gen_atlas.py — re-run that script and paste its output
 * here if the sprite set changes.
 */

import { ASSET_VERSION } from "../config.js";

const W = 18, H = 26; // logical cell size (matches sprite_lib)
const PX = 3; // upscale factor baked into atlas.png
const SRC_W = W * PX, SRC_H = H * PX; // 54 x 78 px per cell in the PNG
const ASPECT = W / H;

export type AnimState = "idle" | "walk" | "attack" | "hurt";
interface FrameRange {
  col: number;
  n: number;
  fps: number;
}
interface SpriteDef {
  row: number;
  states: Partial<Record<AnimState, FrameRange>>;
}

const SPRITES: Record<string, SpriteDef> = {
  hero: { row: 0, states: { idle: { col: 0, n: 2, fps: 3 }, walk: { col: 2, n: 4, fps: 9 }, attack: { col: 6, n: 3, fps: 18 } } },
  werewolf: { row: 1, states: { idle: { col: 0, n: 2, fps: 3 }, walk: { col: 2, n: 4, fps: 9 }, attack: { col: 6, n: 3, fps: 18 } } },
  wolf: { row: 2, states: { idle: { col: 0, n: 2, fps: 3 }, walk: { col: 2, n: 4, fps: 9 }, attack: { col: 6, n: 3, fps: 18 } } },
  bandit: { row: 3, states: { idle: { col: 0, n: 2, fps: 3 }, walk: { col: 2, n: 4, fps: 9 }, attack: { col: 6, n: 3, fps: 18 } } },
  draugr: { row: 4, states: { idle: { col: 0, n: 2, fps: 3 }, walk: { col: 2, n: 4, fps: 9 }, attack: { col: 6, n: 3, fps: 18 } } },
  draugr_overlord: { row: 5, states: { idle: { col: 0, n: 2, fps: 3 }, walk: { col: 2, n: 4, fps: 9 }, attack: { col: 6, n: 3, fps: 18 } } },
  dwarven_battlemage: { row: 6, states: { idle: { col: 0, n: 2, fps: 3 }, walk: { col: 2, n: 4, fps: 9 }, attack: { col: 6, n: 3, fps: 18 } } },
  dwarven_warlord: { row: 7, states: { idle: { col: 0, n: 2, fps: 3 }, walk: { col: 2, n: 4, fps: 9 }, attack: { col: 6, n: 3, fps: 18 } } },
  npc_legion: { row: 8, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_stormcloaks: { row: 9, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_companions: { row: 10, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_college: { row: 11, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_thievesGuild: { row: 12, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_darkBrotherhood: { row: 13, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_blades: { row: 14, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_bards: { row: 15, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_courier: { row: 16, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_arngeir: { row: 17, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_calcelmo: { row: 18, states: { idle: { col: 0, n: 2, fps: 2 } } },
  npc_merchant: { row: 19, states: { idle: { col: 0, n: 2, fps: 2 } } },
};

class SpriteAtlas {
  private img = new Image();
  ready = false;

  /** Kick off loading the atlas PNG (idempotent). */
  load(src = "assets/atlas.png"): void {
    if (this.img.src) return;
    this.img.onload = () => {
      this.ready = true;
    };
    this.img.onerror = () => {
      console.warn(`[Atlas] failed to load ${src}; using procedural sprites.`);
    };
    this.img.src = `${src}?v=${ASSET_VERSION}`;
  }

  /** True only once the PNG is decoded and the sprite exists. */
  has(name: string): boolean {
    return this.ready && name in SPRITES;
  }

  /**
   * Draw an animated sprite, feet-anchored. `state` picks the frame block
   * (falling back to idle); the frame cycles on `animTime` at the state's fps,
   * except an `attack` with an explicit `phase` (0..1) maps straight to the
   * swing's progress so it can't desync from the hitbox. Mirrors when `flip`.
   * Returns false (so the caller can fall back) if the atlas isn't ready / the
   * sprite is unknown.
   */
  drawAnimated(
    ctx: CanvasRenderingContext2D,
    name: string,
    state: AnimState,
    cx: number,
    feetY: number,
    sh: number,
    flip: boolean,
    animTime: number,
    phase?: number,
  ): boolean {
    const def = SPRITES[name];
    if (!this.ready || !def) return false;
    const st = def.states[state] ?? def.states.idle ?? Object.values(def.states)[0];
    if (!st) return false;
    const frame =
      state === "attack" && phase != null
        ? Math.min(st.n - 1, Math.max(0, Math.floor(phase * st.n)))
        : Math.floor(animTime * st.fps) % st.n;
    const sx = (st.col + frame) * SRC_W;
    const sy = def.row * SRC_H;
    const sw = sh * ASPECT;
    const dx = cx - sw / 2;
    const dy = feetY - sh;
    const prevSmooth = ctx.imageSmoothingEnabled;
    ctx.imageSmoothingEnabled = false;
    if (flip) {
      ctx.save();
      ctx.translate(dx + sw, dy);
      ctx.scale(-1, 1);
      ctx.drawImage(this.img, sx, sy, SRC_W, SRC_H, 0, 0, sw, sh);
      ctx.restore();
    } else {
      ctx.drawImage(this.img, sx, sy, SRC_W, SRC_H, dx, dy, sw, sh);
    }
    ctx.imageSmoothingEnabled = prevSmooth;
    return true;
  }

  /** Back-compat: draw the static idle frame (used by overlays / simple callers). */
  blitFeet(ctx: CanvasRenderingContext2D, name: string, cx: number, feetY: number, sh: number, flip: boolean): boolean {
    return this.drawAnimated(ctx, name, "idle", cx, feetY, sh, flip, 0);
  }
}

export const atlas = new SpriteAtlas();
