/**
 * Runtime texture atlas for the flat pixel-art character sprites (generated by
 * tools/gen_atlas.py -> assets/atlas.png). Loaded async at startup; until it's
 * ready, callers fall back to the procedural drawing in sprites.ts.
 *
 * The index below is emitted verbatim by gen_atlas.py — re-run that script and
 * paste its output here if the sprite set changes.
 */

const W = 18, H = 26; // logical cell size (matches sprite_lib)
const PX = 3; // upscale factor baked into atlas.png (see tools/gen_atlas.py)
const SRC_W = W * PX, SRC_H = H * PX; // 54 x 78 px per cell in the PNG
const ASPECT = W / H;

const SPRITES: Record<string, [number, number]> = {
  hero: [0, 0],
  werewolf: [1, 0],
  wolf: [2, 0],
  bandit: [3, 0],
  draugr: [4, 0],
  draugr_overlord: [5, 0],
  dwarven_battlemage: [6, 0],
  dwarven_warlord: [7, 0],
  npc_legion: [0, 1],
  npc_stormcloaks: [1, 1],
  npc_companions: [2, 1],
  npc_college: [3, 1],
  npc_thievesGuild: [4, 1],
  npc_darkBrotherhood: [5, 1],
  npc_blades: [6, 1],
  npc_bards: [7, 1],
  npc_courier: [0, 2],
  npc_arngeir: [1, 2],
  npc_calcelmo: [2, 2],
  npc_merchant: [3, 2],
};

class SpriteAtlas {
  private img = new Image();
  ready = false;

  /** Kick off loading the atlas PNG (idempotent). */
  load(src = "assets/atlas.png"): void {
    if (this.img.src) return;
    this.img.onload = () => {
      this.ready = true;
    };
    this.img.onerror = () => {
      console.warn(`[Atlas] failed to load ${src}; using procedural sprites.`);
    };
    this.img.src = src;
  }

  /** True only once the PNG is decoded and the sprite exists. */
  has(name: string): boolean {
    return this.ready && name in SPRITES;
  }

  /**
   * Draw sprite `name` at on-screen height `sh` (width derives from the cell
   * aspect), centered horizontally on `cx` with its feet at `feetY`. Mirrors
   * horizontally when `flip` (i.e. the entity faces left). Returns false if the
   * atlas isn't ready / the name is unknown so the caller can fall back.
   */
  blitFeet(ctx: CanvasRenderingContext2D, name: string, cx: number, feetY: number, sh: number, flip: boolean): boolean {
    const cell = SPRITES[name];
    if (!this.ready || !cell) return false;
    const sw = sh * ASPECT;
    const dx = cx - sw / 2;
    const dy = feetY - sh;
    const sx = cell[0] * SRC_W;
    const sy = cell[1] * SRC_H;
    const prevSmooth = ctx.imageSmoothingEnabled;
    ctx.imageSmoothingEnabled = false;
    if (flip) {
      ctx.save();
      ctx.translate(dx + sw, dy);
      ctx.scale(-1, 1);
      ctx.drawImage(this.img, sx, sy, SRC_W, SRC_H, 0, 0, sw, sh);
      ctx.restore();
    } else {
      ctx.drawImage(this.img, sx, sy, SRC_W, SRC_H, dx, dy, sw, sh);
    }
    ctx.imageSmoothingEnabled = prevSmooth;
    return true;
  }
}

export const atlas = new SpriteAtlas();
